### ISSUE TITLE
Outdated version of OpenSSL in Vitamio

### ISSUE THREAD

**Issue by natuan0rg** [yixia/VitamioBundle#184]
I'vd applied vitamio player for my android app, currently, GG play pushed to me one security warming message:

"Hello,

One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible. For more information about the most recent security vulnerability in OpenSSL, please see http://www.openssl.org/news/secadv_20140605.txt.

Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

Regards,

Google Play Team

©2014 Google Inc.
1600 Amphitheatre Parkway
Mountain View, CA 94043

Email preferences: You have received this mandatory email service announcement to update you about important changes to your Google Play account."

I've using 4.2.2

I want to make sure that when I upgrade to 4.2.6 then the issue will be resolved

Thanks

**Comment by dochathuc** [comment]
@crossle still waiting?

**Comment by AbelValdez** [comment]
hi i have the same issue can you post the status of the update  please!! 

regards

**Comment by crossle** [comment]
Try https://github.com/yixia/VitamioBundle/commit/a216a0791eb250a117845e105c42e49b08b5244f

**Comment by AbelValdez** [comment]
Hi, Crossle, 

I need remplace the libvinit.so of vitamio bundle? 

regards!

**Comment by crossle** [comment]
No need.

**Comment by mkiisoft** [comment]
@crossle so se only need to add the new "raw" folder file to our proyect (or the bundle) right?

**Comment by crossle** [comment]
You only need update vitamio project.

**Comment by mkiisoft** [comment]
Great! I think all douths are clear for everyone. We should close this issue. The comments have all answers.

**Comment by rendev** [comment]
Hello @crossle, could you please version with updated version of OpenSSL for intel processors too?
After updated library, i had a crash that "Native libs libffmpeg.so not exists!" for asus zenfone 6.

**Comment by josemoreno10** [comment]
hello @crossle  I need to update Vitamio with updated version of OpenSSL but I do not know how 4.2.2 version 4.2.6 I do not find, you help me, I have the same warning from google play

"One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible. For more information about the most recent security vulnerability in OpenSSL, please see http://www.openssl.org/news/secadv_20140605.txt.

Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

Regards,

Google Play Team"

**Comment by jeon-gyungmin** [comment]
Hello @crossle I have a same issue. Where is next version? Plz help me. 

This app uses software that contains security vulnerabilities for users.

Below is the list of vulnerabilities and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.

Vulnerability   APK Version(s)
OpenSSL
The vulnerabilities were fixed in OpenSSL versions beginning with 1.0.1h, 1.0.0m, and 0.9.8za. To confirm your OpenSSL version, you can do a grep via:

$ unzip -p YourApp.apk | strings | grep "OpenSSL"

For more information about the vulnerability, please see this OpenSSL Security Advisory. For other technical questions, please post to https://www.stackoverflow.com/questions and use the tags "android-security" and "openssl."

2
To confirm you’ve upgraded correctly, submit the updated version of your app to the Developer Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.

**Comment by krishna18787** [comment]
Hi,

I am getting below message from Google play :: please look at and let me know the solution:

Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. If you’re using a 3rd party library that bundles OpenSSL, you’ll need to upgrade it to a version that bundles OpenSSL 1.02f/1.01r or higher.

The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. The latest versions of OpenSSL can be downloaded here. To confirm your OpenSSL version, you can do a grep search for ($ unzip -p YourApp.apk | strings | grep "OpenSSL").

To confirm you’ve upgraded correctly, submit the updated version to the Developer Console and check back after five hours. If the app hasn’t been correctly upgraded, we will display a warning.

Please i need solution  urgently. So please give me some suggestion for how to upgrade SSL version of Vitamio ..I will be highly obliged for your support..
