### ISSUE TITLE
update ffmpeg 2.7

### ISSUE THREAD

**Issue by msdos2** [yixia/VitamioBundle#301]
Is it possible to upgrade to the latest version of ffmpeg ? .Thank you

**Comment by MythodeaLoL** [comment]
Yes, you can even compile your version of ffmpeg/vitamio and replace the files in libarm.so upgrading.
<b>[CLOSE ISSUE PLEASE]</b>

**Comment by msdos2** [comment]
hello, the trouble is that I want to compile ffmpeg version 2.7, and I copy it in the ffmpg-vitamio folder and I want to compile it with rtmp, but it fails if I try to compile ffmpg 2.7, can you help me with the right steps to compile it properly please ? thank you.

**Comment by MythodeaLoL** [comment]
Sorry, i cant help with compilers.

**Comment by gen2brain** [comment]
It is not possible? You can customize current ffmpeg build, but you can not update. We will need that part of vitamio that is closed source for that. FFmpeg API has changed since I think, vitamio will work only with version 2.1, at least I tried to update, I tried with 2.2, 2.3 etc. and then back to 2.1 because that was the only one that worked.
