### ISSUE TITLE
Google Play Security alert - Vitamio SDK containing world-writable code

### ISSUE THREAD

**Issue by KrishnaGujju** [yixia/VitamioBundle#336]
Google Play Security alert message :
Security alert
Your app utilizes a version of Vitamio, a multimedia library used for playing various types of media files, containing a security vulnerability.
Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK. Beginning 14 March 2016, Google Play will block publishing of any new apps or updates that use pre-5.0 versions of Vitamio.
The vulnerability was addressed in Vitamio v5.0. The latest versions of Vitamio can be downloaded on the Vitamio website. You can confirm your Vitamio version by checking if the SDK includes libs/armeabi-v7a/libvinit.so or libs/armeabi/libvinit.so. If either file is present, the SDK needs to be upgraded. For help upgrading, see the Vitamio support documentation. If you’re using a 3rd party library that bundles Vitamio, please notify the 3rd party and work with them to address this.
To confirm you’ve upgraded correctly, submit the updated version to the Developer Console and check back after five hours. If the app hasn’t been correctly upgraded, we will display a warning.
The vulnerability is due to the Vitamio SDK containing world-writable code. For more information about the vulnerability, please see this NowSecure blog post. For other technical questions, you can post toStack Overflow and use the tags “android-security” and “vitamio.”
While these specific issues may not affect every app that uses Vitamio, it’s best to stay up to date on all security patches. Apps with vulnerabilities that expose users to risk of compromise may be considered dangerous products in violation of the Content Policy and section 4.4 of the Developer Distribution Agreement.
Apps must also comply with the Developer Distribution Agreement and Content Policy. If you feel we have sent this warning in error, contact our policy support team through the Google Play Developer Help Center.

**Comment by KrishnaGujju** [comment]
The vulnerability is due to the Vitamio SDK containing world-writable code. For more information about the vulnerability, please see this NowSecure blog post - 
https://www.nowsecure.com/blog/2015/08/10/world-writable-code-is-bad-mmmmkay/

**Comment by atul14** [comment]
@crosslesong are you addressing this issue?

**Comment by mhcpan** [comment]
Go to https://www.vitamio.org/Download/  and download 5.0
You can only find it at Chinese platform. So switch to "Chinese page" if you still find version 4.2( by clicking the Chinese words next to Vitamio logo.)

However, I can't make it work with audio streaming. If anyone have successful implementation, please share it.

**Comment by MythodeaLoL** [comment]
@atul14 the user <b>crosslesong</b> is only for posting code, I believe that anyone who might help is the <b>crosle</b>.

<i>But he's well away and busy with his other project, do not be surprised if he does not answer.</i>

There is no one officially supporting version 5.0.0, then you who are using are basically alone and unsupported help. You can compile your own libarm the vitamio, updating it as needed. Version 4.2 is still the best in my opinion. I do not consider leaving it.

Sorry the English, must have seen that I am not fluent. hahaha

**Comment by atul14** [comment]
@FloridaStream Thanks for pointing out. In that case we hit a stalemate. Because Google is pointing out to upgrade to 5.0 due to Security concerns. But 5.0.0 is not working for audio streams specifically, as @KrishnaGujju shared.

Is there a way we can keep using 4.x and still comply with the Google security concerns?

**Comment by TheModerator** [comment]
@Atul14 Yes, and No. If your app has any special permissions (so, for example, sending texts, or making calls) then by using Vitamio <5.x, you're letting any app have those permissions This is NOT ideal at all. If it has no special permissions, then in theory it's okay and the impact is minimal, but that is not to say it's a good thing.

In example; at minimum, you're using Vitamio for streaming audio from the internet, so your app requires the internet permission. Therefore, any app on your device has the internet permission even if the user did not give the app it. Some might claim it's a moot point because 'all apps use the internet these days anyway and nobody would decline an app access to the internet anyway'. From a security standpoint, it's just plain bad practice. We live in an age where we should have a zero-tolerance to any vulnerability, so allowing them just because it's of your opinion that there isn't any real harm done is simply not acceptable.

With all that said, you can circumvent google's detection of sub-5.0 versions relatively easy, if that's what you're asking ;)

**Comment by EugeniyGubar** [comment]
@TheModerator, could you please clarify how to circumvent detection of 4.2.2 version at Google Play? I downloaded version 5.0 and it doesn't work, so I want to get back to 4.2.2

**Comment by davidbilly** [comment]
Hi Guys,

I been upgraded to Vitamio lib 5.0 for my app. But 2 days after published on Google Play Store , Google alert still there. 

Anyone facing this issue?

Please assist me :(

**Comment by Vaporexpress** [comment]
@davidbilly Don't worry my App has taken a week before the warning disappears.

**Comment by davidbilly** [comment]
@Vaporexpress  Thanks for reply, my app warning was removed yesterday night : D

but my friend app that haven't update to vitamio 5.0, Google removed warning for him too lol

**Comment by jimztercrack** [comment]
Hello! I already update my project to vitamio 5 from: https://www.vitamio.org/en/Download/   but I can't update my app in google play  they still say that my app have vulnerabilities, can someone help me wit this issue please; thanks.

**Comment by jimztercrack** [comment]
This is the notification from google play: 

Hello Google Play Developer,

We rejected SINART, with package name cr.go.sinart.sinart, for violating our Malicious Behavior policy. If you submitted an update, the previous version of your app is still available on Google Play.

This app uses software that contains security vulnerabilities for users.

Below is the list of vulnerabilities and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.
Vulnerability   APK Version(s)
Vitamio

The vulnerabilities were fixed in Vitamio v.5.0 and higher. To confirm the vulnerability, check to see if your SDK includes libs/armeabi-v7a/libvinit.so or libs/armeabi/libvinit.so. If either file is present, the SDK needs to be upgraded.

You can find more information and next steps in this Google Help Center article.
    4

To confirm you’ve upgraded correctly, submit the updated version of your app to the Developer Console and check back after five hours to make sure the warning is gone.

While these vulnerabilities may not affect every app that uses this software, it’s best to stay up to date on all security patches. Make sure to update any libraries in your app that have known security issues, even if you're not sure the issues are relevant to your app.

Apps must also comply with the Developer Distribution Agreement and Developer Program Policies.

If you feel we have made this determination in error, please reach out to our policy support team through the Google Play Developer Help Center.

Best,

The Google Play Team

**Comment by Vaporexpress** [comment]
@jimztercrack 
First was [this notification](https://support.google.com/faqs/answer/6365106), a vulnerability that fix Vitamio v5.0 which come with lack support for armeabi devices in a project almost entirely abandoned.

> Beginning 14 March 2016, Google Play will block publishing of any new apps or updates that use pre-5.0 versions of Vitamio.

Now [this notification](https://support.google.com/faqs/answer/6376725) which it affects all native libraries, and Vitamio no longer supported so you need replace Vitamio on your App with other options.

> Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL.  

My options:
- ExoPlayer (from Google) in java (no vulnerabilities affects your Apps).
- IJKplayer (or GiraffePlayer flavor): java+native libraries (like Vitamio) that you can easily compile and solve openssl vulnerabilities with an openssl updated version and continous support.

Saludos.

**Comment by MythodeaLoL** [comment]
## This post is outdated.

@Vaporexpress @jimztercrack
Please post here:
#360 Vitamio 5.0.0 Google Play warning: You are using a vulnerable version of OpenSSL
all are focusing the subject here.

**Comment by jimztercrack** [comment]
Thanks! @Vaporexpress now my app is running and published in Google Play  with GiraffePlayer and is better than vitamio thanks for your advice!

**Comment by KrishnaGujju** [comment]
This issue has been addressed in Vitamio 5.0 Hence closing - Vitamio 5.0 can be downloaded from this link https://www.vitamio.org/en/Download/

**Comment by TarunPal3551** [comment]
I am using Vitamio 5.0.2 and can i upload this on playstore.
